In [4]:
import numpy as np #
# In python you can extract the i'th column by A[:, i-1] (notice that the columns are 0 indexed)
A = np.array([[-3, 6,6,6], [7,9,0,2], [42,0,3, -5], [0, 0, 7, 4]])
e3 = np.array([0,0,1,0])
e2 = np.array([0,1,0,0])

print(A)

Ae3 = 3*e3
Ae2 = 3*e2
A4e3_2e2 = A*(Ae3+Ae2)

### YOUR CODE - FILL Ae3, Ae2, A4e3_2e2
### END CODE

print('Ae3: ', Ae3)
print('Ae2: ', Ae2)
print('A(4e3+2e2): ', A4e3_2e2)

[[-3  6  6  6]
 [ 7  9  0  2]
 [42  0  3 -5]
 [ 0  0  7  4]]
Ae3:  [0 0 3 0]
Ae2:  [0 3 0 0]
A(4e3+2e2):  [[ 0 18 18  0]
 [ 0 27  0  0]
 [ 0  0  9  0]
 [ 0  0 21  0]]
